source 'http://ruby.taobao.org'

gem 'rails', '3.2.13'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.

gem 'jquery-rails'

group :test, :development do
  gem 'rspec-rails'
  gem 'webrat'
  gem 'capybara'
end
